name: Formatting
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "*.md"

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}

      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
          args: --config-path=stylua.toml lua/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: formatting"
          branch: ${{ github.head_ref }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
          branch: ${{ github.ref }}
